runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: appengine/index.html
  upload: appengine/index.html

- url: /(.*)
  static_files: appengine/\1
  upload: appengine/(.*)
